#!/bin/sh

# This script is used to setup the environment for the project.
# It will install all the dependencies and create the virtual environment.

# Check if pyenv is installed
if ! [ -x "$(command -v pyenv)" ]; then
  echo "Error: pyenv is not installed."
  exit 1
fi

if ! [ -d "venv" ]; then
  echo "Creating virtual environment..."
  python -m venv venv
fi

echo "Activating virtual environment..."
source venv/bin/activate

echo "Installing dependencies..."
pip install -r requirements.txt

echo "Setting up pre-commit hooks..."
pre-commit install

echo "Done."